2024-01-13 19:59:10,875 INFO    MainThread:14364 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-01-13 19:59:10,875 INFO    MainThread:14364 [wandb_setup.py:_flush():76] Configure stats pid to 14364
2024-01-13 19:59:10,875 INFO    MainThread:14364 [wandb_setup.py:_flush():76] Loading settings from /home/anto/.config/wandb/settings
2024-01-13 19:59:10,875 INFO    MainThread:14364 [wandb_setup.py:_flush():76] Loading settings from /home/anto/University/Driving-Visual-Attention/wandb/settings
2024-01-13 19:59:10,875 INFO    MainThread:14364 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-13 19:59:10,875 INFO    MainThread:14364 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-13 19:59:10,875 INFO    MainThread:14364 [wandb_init.py:_log_setup():526] Logging user logs to /home/anto/University/Driving-Visual-Attention/wandb/run-20240113_195910-gskkifmp/logs/debug.log
2024-01-13 19:59:10,875 INFO    MainThread:14364 [wandb_init.py:_log_setup():527] Logging internal logs to /home/anto/University/Driving-Visual-Attention/wandb/run-20240113_195910-gskkifmp/logs/debug-internal.log
2024-01-13 19:59:10,875 INFO    MainThread:14364 [wandb_init.py:init():566] calling init triggers
2024-01-13 19:59:10,875 INFO    MainThread:14364 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-01-13 19:59:10,875 INFO    MainThread:14364 [wandb_init.py:init():591] re-initializing run, found existing run on stack: l3wuk8xm
2024-01-13 19:59:10,877 INFO    MainThread:14364 [wandb_run.py:_finish():1962] finishing run vesuvio-erutta/CNNbaseline best/l3wuk8xm
2024-01-13 19:59:10,878 ERROR   MainThread:14364 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-01-13 19:59:10,878 INFO    MainThread:14364 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-13 19:59:10,878 INFO    MainThread:14364 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-01-13 19:59:10,879 INFO    MainThread:14364 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-13 19:59:10,879 INFO    MainThread:14364 [wandb_run.py:_restore():2185] restore
2024-01-13 19:59:10,879 INFO    MainThread:14364 [wandb_run.py:_restore():2191] restore done
2024-01-13 19:59:17,293 INFO    MainThread:14364 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-01-13 19:59:17,293 INFO    MainThread:14364 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-01-13 19:59:17,296 INFO    MainThread:14364 [wandb_run.py:_footer_sync_info():3816] logging synced files
2024-01-13 19:59:17,401 INFO    MainThread:14364 [wandb_init.py:init():616] starting backend
2024-01-13 19:59:17,401 INFO    MainThread:14364 [wandb_init.py:init():620] setting up manager
2024-01-13 19:59:17,402 INFO    MainThread:14364 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-13 19:59:17,402 INFO    MainThread:14364 [wandb_init.py:init():628] backend started and connected
2024-01-13 19:59:17,404 INFO    MainThread:14364 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-13 19:59:17,404 INFO    MainThread:14364 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-13 19:59:17,404 INFO    MainThread:14364 [wandb_init.py:init():720] updated telemetry
2024-01-13 19:59:17,479 INFO    MainThread:14364 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-01-13 19:59:17,751 WARNING MainThread:14364 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 756, in init
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
